# Rime default settings
# encoding: utf-8

config_version: "0.40"

schema_list:
  - schema: moqi_wan_flypymo # 墨奇万象·小鹤+墨奇形
  # - schema: moqi_wan_flypy # 墨奇万象·小鹤+鹤形 鹤形+鹤拼, 小鹤官方就只有8000字左右
  # - schema: moqi_single_xh # 墨奇码·顶屏版·小鹤双拼，为了4码自动上屏 只收录了8000字
  # - schema: moqi_xh # 墨奇辅助码 鹤拼版 大词库版本 非自动上屏，支持4万字
  # - schema: moqi_wan_flypyhu # 墨奇万象·小鹤+虎形
  # - schema: moqi_wan_jdh  # 墨奇万象·小鹤+简单鹤
  # - schema: moqi_wan_quanpin_moqi  # 墨奇万象·全拼+墨奇形

switcher:
  caption: options
  hotkeys:
    - F4
  save_options:
    - ascii_mode
    - full_shape
    - traditionalization
    - emoji
    - chaifen
    - big_char_set # 大字集 小字集
    - mars
    - ascii_punct
  fold_options: true
  abbreviate_options: true
  option_list_separator: "／"

menu:
  page_size: 9 #候选项数

style:
  horizontal: false #横排为true

punctuator:
  full_shape:
    " ": { commit: "　" }
    ",": { commit: ， }
    ".": { commit: 。 }
    "<": [《, 〈, «, ‹]
    ">": [》, 〉, », ›]
    "/": [／, ÷]
    "?": { commit: ？ }
    ";": { commit: ； }
    ":": { commit: ： }
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': [、, ＼]
    "|": [·, ｜, "§", "¦"]
    "`": ｀
    "~": ～
    "!": { commit: ！ }
    "@": [＠, ☯]
    "#": [＃, ⌘]
    "%": [％, "°", "℃"]
    "$": [￥, "$", "€", "£", "¥", "¢", "¤"]
    "^": { commit: …… }
    "&": ＆
    "*": [＊, ·, ・, ×, ※, ❂]
    "(": （
    ")": ）
    "-": －
    "_": ——
    "+": ＋
    "=": ＝
    "[": [「, 【, 〔, ［]
    "]": [」, 】, 〕, ］]
    "{": [『, 〖, ｛]
    "}": [』, 〗, ｝]
  half_shape:
    ",": "，"
    ".": "。"
    "<": "《"
    ">": "》"
    "/": [/, ÷]
    "?": "？"
    ";": "；"
    ":": "："
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    # '"' : { commit: '“”' } # 直接输出一对引号
    '\': "、"
    "|": ["·", "|", "｜", "§", "¦"]
    "`": "、"
    "~": "~"
    "!": "！"
    "@": "@"
    "#": "#"
    "%": "%"
    "$": "¥"
    "^": "……"
    "&": "&"
    "*": "*"
    "(": "（"
    ")": "）"
    "-": "-"
    "_": ——
    "+": "+"
    "=": "="
    "[": "【"
    "]": "】"
    "{": "「"
    "}": "」"

key_binder:
  bindings:
    # Tab / Shift+Tab 切换光标至下/上一个拼音
    - { when: composing, accept: Shift+Tab, send: Shift+Left }
    - { when: composing, accept: Tab, send: Shift+Right }

    # Option/Alt + ←/→ 切换光标至下/上一个拼音
    - { when: composing, accept: Alt+Left, send: Shift+Left }
    - { when: composing, accept: Alt+Right, send: Shift+Right }

    # 翻页 , .
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }

    - { when: always, toggle: ascii_punct, accept: Control+Shift+3 } # 切换中英标点
    - { when: always, toggle: ascii_punct, accept: Control+Shift+numbersign } # 切换中英标点
    - { when: always, toggle: traditionalization, accept: Control+Shift+4 } # 切换简繁
    - { when: always, toggle: traditionalization, accept: Control+Shift+dollar } # 切换简繁

    # 将小键盘 0~9 . + - * / 映射到主键盘
    # 使计算器(V1+2*3)可使用小键盘输入
    # 数字金额大写的 Lua 如 R1234.5678 可使用小键盘输入
    - { accept: KP_0, send: 0, when: composing }
    - { accept: KP_1, send: 1, when: composing }
    - { accept: KP_2, send: 2, when: composing }
    - { accept: KP_3, send: 3, when: composing }
    - { accept: KP_4, send: 4, when: composing }
    - { accept: KP_5, send: 5, when: composing }
    - { accept: KP_6, send: 6, when: composing }
    - { accept: KP_7, send: 7, when: composing }
    - { accept: KP_8, send: 8, when: composing }
    - { accept: KP_9, send: 9, when: composing }
    - { accept: KP_Decimal, send: period, when: composing }
    - { accept: KP_Multiply, send: asterisk, when: composing }
    - { accept: KP_Add, send: plus, when: composing }
    - { accept: KP_Subtract, send: minus, when: composing }
    - { accept: KP_Divide, send: slash, when: composing }

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_code
    Shift_R: commit_code
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
