# Rime default settings
# encoding: utf-8

config_version: "0.50"

schema_list:
  - schema: moqi_wan_flypymo_colemak # 墨奇万象·小鹤+Colemak键位
  - schema: moqi_wan_flypymo # 墨奇万象·小鹤+墨奇形（推荐）
  - schema: moqi_single_xh # 墨奇码·顶屏版·小鹤双拼，为了 4 码自动上屏，仅收录约 8000 字
  # - schema: moqi_wan_zrm # 墨奇·自然码+自然码部首辅助码
  # - schema: moqi_wan_flypy # 墨奇·小鹤+鹤形
  # - schema: moqi_wan_zrm_hx # 墨奇·自然码+汉心码辅助码
  # - schema: moqi_wan_ms_wb # 墨奇·微软+五笔
  # - schema: moqi_wan_sogou # 墨奇·搜狗+墨奇形
  # - schema: moqi_wan_flypyhu # 墨奇·小鹤+虎形
  # - schema: moqi_wan_jdh # 墨奇·小鹤+简单鹤
  # - schema: moqi_wan_quanpin_moqi # 墨奇·全拼+墨奇形
  # - schema: moqi_wan_abc_mo # 墨奇·智能 ABC 双拼+墨奇

switcher:
  caption: options
  hotkeys:
    - F4
  save_options:
    - ascii_mode
    - full_shape
    - traditionalization
    - emoji
    - chaifen
    - mars
    - ascii_punct
  fold_options: true
  abbreviate_options: true
  option_list_separator: "／"

key_binder:
  bindings:

menu:
  page_size: 9 #候选项数

style:
  horizontal: true #横排为true

punctuator:
  full_shape:
    " ": { commit: "　" }
    ",": { commit: ， }
    ".": { commit: 。 }
    "<": [《, 〈, «, ‹]
    ">": [》, 〉, », ›]
    "/": [／, ÷]
    "?": { commit: ？ }
    ";": { commit: ； }
    ":": { commit: ： }
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    '\': [、, ＼]
    "|": [·, ｜, "§", "¦"]
    "`": ｀
    "~": ～
    "!": { commit: ！ }
    "@": [＠, ☯]
    "#": [＃, ⌘]
    "%": [％, "°", "℃"]
    "$": [￥, "$", "€", "£", "¥", "¢", "¤"]
    "^": { commit: …… }
    "&": ＆
    "*": [＊, ·, ・, ×, ※, ❂]
    "(": （
    ")": ）
    "-": －
    "_": ——
    "+": ＋
    "=": ＝
    "[": [「, 【, 〔, ［]
    "]": [」, 】, 〕, ］]
    "{": [『, 〖, ｛]
    "}": [』, 〗, ｝]
  half_shape:
    ",": "，"
    ".": "。"
    "<": "《"
    ">": "》"
    "/": [/, ÷]
    "?": "？"
    ";": "；"
    ":": "："
    "'": { pair: ["‘", "’"] }
    '"': { pair: ["“", "”"] }
    # '"' : { commit: '“”' } # 直接输出一对引号
    '\': "、"
    "|": ["·", "|", "｜", "§", "¦"]
    "`": "、"
    "~": "~"
    "!": "！"
    "@": "@"
    "#": "#"
    "%": "%"
    "$": "¥"
    "^": "……"
    "&": "&"
    "*": "*"
    "(": "（"
    ")": "）"
    "-": "-"
    "_": ——
    "+": "+"
    "=": "="
    "[": "【"
    "]": "】"
    "{": "「"
    "}": "」"

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_code
    Shift_R: commit_code
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
